name: osu-wiki continuous integration

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - edited

jobs:
  ci:
    name: changed files
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        shell: bash
        run: |
          # Create the repository with a different default branch name to avoid confusion with the real "master" branch of ppy/osu-wiki
          git init -b pull-request-merge

          # Fetch the PR merge commit and all history, but ignore file contents
          git fetch --filter=blob:none \
            'https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git' \
            '${{ github.sha }}'

          # Update HEAD, index, and current branch ref to the fetched commit. Reset working tree and download required files
          git reset --hard FETCH_HEAD

      - name: inspect binary file sizes
        shell: bash
        run: bash scripts/ci/inspect_binary_file_sizes.sh ${{ github.sha }} ${{ github.sha }}

      - name: set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 16

      - name: install remark
        run: npm ci

      - name: run remark on changed files
        run: bash scripts/ci/run_remark.sh ${{ github.sha }}

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          cache: pip
          cache-dependency-path: scripts/requirements.txt
          python-version: 3.x

      - name: set up CI dependencies
        run: pip install -r scripts/requirements.txt

      - name: run yamllint on .yaml and .md files
        run: |
          python scripts/ci/run_yamllint.py --config .yamllint.yaml

      - name: find broken wikilinks
        shell: bash
        env:
          PULL_REQUEST_TAG: 'SKIP_WIKILINK_CHECK'
        run: |
          if ${{ contains(github.event.pull_request.body, env.PULL_REQUEST_TAG) }}; then
            echo "::notice::Broken wikilink check suppressed ($PULL_REQUEST_TAG tag found in the pull request)"
            exit 0
          fi

          ARTICLES=$( git diff --diff-filter=d --name-only ${{ github.sha }}^ ${{ github.sha }} "wiki/**/*.md" "news/*.md" )
          osu-wiki-tools check-links --target $ARTICLES

      - name: check if translations are marked as outdated
        shell: bash
        env:
          PULL_REQUEST_TAG: 'SKIP_OUTDATED_CHECK'
        run: |
          if ${{ contains(github.event.pull_request.body, env.PULL_REQUEST_TAG) }}; then
            echo "::notice::Outdated articles check suppressed ($PULL_REQUEST_TAG tag found in the pull request)"
            exit 0
          fi
          # get the first commit of the branch associated with the PR; GitHub's ubuntu-latest has curl/jq: https://github.com/actions/virtual-environments
          FIRST_PR_COMMIT_HASH=$( curl -sS ${{ github.event.pull_request.commits_url }}?per_page=1 | jq -r '.[0].sha' || true )
          osu-wiki-tools check-outdated-articles --workflow --base-commit ${{ github.sha }} --outdated-since $FIRST_PR_COMMIT_HASH
