name: Sync from osu! upstream

on:
  workflow_dispatch:
    inputs:
      backup:
        default: false
        description: "Create a backup of your target branch? (true/false)"
        required: true
        type: boolean
      overwrite:
        default: false
        description: "Overwrite any changes in the target repository? (true/false)"
        required: true
        type: boolean

jobs:
  sync:
    name: Execute Sync Task
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Begin Pull Task
        run: |
          branch_name="$(git branch --show-current)"
          backup_branch_name="$branch_name-backup"

          if ${{ inputs.backup }}; then
            git push origin "HEAD:$backup_branch_name"
          fi

          git remote add upstream https://github.com/ppy/osu-wiki
          git fetch upstream master

          if ${{ inputs.overwrite }}; then
            echo "::warning::You've set force-overwriting to true. This will overwrite your changes."
            git push --force origin "FETCH_HEAD:$branch_name"
          else
            git config user.name '${{ github.actor }}'
            git config user.email '${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com'
            git merge FETCH_HEAD
            git push origin "$branch_name"
          fi
